export type CanopyType = {
  id: string;
  name: string;
  category: string;
  price: number;
  emoji: string;
  desc: string;
  hollow: string[];
  extras?: string[];
};

// Sumber: Katalog Living Space Pro (harga mulai / m²)
export const CANOPY_TYPES: CanopyType[] = [
  {
    id: "spandek",
    name: "Kanopi Spandek Pasir",
    category: "Standar",
    price: 600_000,
    emoji: "🏗️",
    desc: "Ekonomis, ringan & tahan lama",
    hollow: [
      "Hollow galvanis 40×60 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap spandek pasir", "Talang air plat besi"],
  },
  {
    id: "alderon-single",
    name: "Kanopi Alderon Single Layer",
    category: "Standar",
    price: 750_000,
    emoji: "🛡️",
    desc: "Anti bocor, peredam panas dasar",
    hollow: [
      "Hollow galvanis 40×60 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Single Layer", "Talang air plat besi"],
  },
  {
    id: "alderon-double",
    name: "Kanopi Alderon Double Layer",
    category: "Standar",
    price: 850_000,
    emoji: "🛡️",
    desc: "Peredam panas & suara lebih optimal",
    hollow: [
      "Hollow galvanis 40×60 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Double Layer", "Talang air plat besi"],
  },
  {
    id: "cremona-alderon",
    name: "Kanopi Cremona + Alderon Double",
    category: "Model Cremona",
    price: 850_000,
    emoji: "🏛️",
    desc: "Desain minimalis model cremona",
    hollow: [
      "Hollow galvanis 40×40 frame",
      "Hollow galvanis 40×20 frame",
      "Hollow galvanis 40×60 subframe",
    ],
    extras: ["Atap Alderon Double Layer"],
  },
  {
    id: "cordoba-alderon",
    name: "Kanopi Cordoba + Alderon Double",
    category: "Model Cordoba",
    price: 850_000,
    emoji: "🏰",
    desc: "Frame kokoh, tampilan elegan",
    hollow: [
      "Hollow galvanis 40×80 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Hollow galvanis 40×20 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Double Layer", "Talang air plat besi"],
  },
  {
    id: "cordoba-acp",
    name: "Kanopi Cordoba + Alderon + Plafon ACP",
    category: "Model Cordoba",
    price: 900_000,
    emoji: "✨",
    desc: "Tampil premium dengan plafon ACP putih",
    hollow: [
      "Hollow galvanis 40×80 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Hollow galvanis 40×20 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Double Layer", "Plafon ACP white", "Talang air plat besi"],
  },
  {
    id: "alderon-transparan",
    name: "Kanopi Alderon Transparan",
    category: "Transparan",
    price: 1_000_000,
    emoji: "🌤️",
    desc: "Tembus cahaya, tetap redam panas",
    hollow: [
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Transparan Double", "Talang air plat besi"],
  },
  {
    id: "twinlite-grecca",
    name: "Kanopi Twinlite Grecca Transparan",
    category: "Transparan",
    price: 1_200_000,
    emoji: "🌫️",
    desc: "Twinlite double layer transparan",
    hollow: [
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Twinlite grecca double layer", "Talang air plat besi"],
  },
  {
    id: "lengkung-alderon-single",
    name: "Kanopi Lengkung Alderon Single",
    category: "Lengkung",
    price: 850_000,
    emoji: "🌈",
    desc: "Desain lengkung estetik",
    hollow: [
      "Hollow galvanis 100×100 tiang",
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Single Layer", "Talang air plat besi"],
  },
  {
    id: "lengkung-alderon-double",
    name: "Kanopi Lengkung Alderon Double",
    category: "Lengkung",
    price: 900_000,
    emoji: "🌈",
    desc: "Lengkung premium peredam panas",
    hollow: [
      "Hollow galvanis 100×100 tiang",
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Atap Alderon Double Layer", "Talang air plat besi"],
  },
  {
    id: "lengkung-solarflat",
    name: "Kanopi Lengkung Solarflat 3mm",
    category: "Lengkung",
    price: 1_300_000,
    emoji: "☀️",
    desc: "Transparan solarflat, model lengkung",
    hollow: [
      "Hollow galvanis 100×100 tiang",
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 40×60 subframe",
      "Hollow galvanis 40×40 profile",
      "Pipa besi 2 inch",
    ],
    extras: ["Solarflat transparan 3mm", "Talang air plat besi"],
  },
  {
    id: "kaca-tempered",
    name: "Kanopi Kaca Tempered 8mm",
    category: "Premium",
    price: 1_500_000,
    emoji: "💎",
    desc: "Estetika premium, mewah & modern",
    hollow: ["Hollow galvanis 50×100 frame", "Hollow galvanis 50×100 subframe"],
    extras: ["Kaca tempered 8mm", "Rangka IWF / HBEAM dihitung sesuai kebutuhan"],
  },
  {
    id: "skylight-alderon",
    name: "Skylight Alderon Double Sleding",
    category: "Skylight",
    price: 900_000,
    emoji: "🪟",
    desc: "Atap buka-tutup dengan katrol manual",
    hollow: ["Hollow galvanis 40×60 frame", "Hollow galvanis 40×60 subframe", "Katrol manual"],
    extras: ["Alderon double layer", "Talang bending Rp 300.000/m (opsional)"],
  },
  {
    id: "skylight-solarflat",
    name: "Skylight Solarflat 3mm",
    category: "Skylight",
    price: 1_300_000,
    emoji: "🪟",
    desc: "Skylight transparan permanent / sleding",
    hollow: ["Hollow galvanis 40×60 frame", "Hollow galvanis 40×60 subframe"],
    extras: [
      "Solarflat 3mm",
      "Opsi sleding katrol +Rp 300rb, otomatis +Rp 100rb (excl. motor Rp 2,5jt)",
    ],
  },
  {
    id: "skylight-kaca",
    name: "Skylight Kaca Tempered",
    category: "Skylight",
    price: 1_500_000,
    emoji: "🪟",
    desc: "Skylight kaca — mewah & terang alami",
    hollow: ["Hollow galvanis 50×100 frame", "Hollow galvanis 50×100 subframe"],
    extras: ["Kaca tempered 8mm", "Opsi sleding katrol Rp 1,8jt/m, otomatis Rp 2,2jt/m"],
  },
  {
    id: "mezanin",
    name: "Kanopi Mezanin (Lantai Tambahan)",
    category: "Konstruksi",
    price: 1_500_000,
    emoji: "🏗️",
    desc: "Include railing balkon, exclude tangga",
    hollow: [
      "Hollow galvanis 100×100 tiang",
      "Hollow galvanis 50×100 frame",
      "Hollow galvanis 50×100 subframe",
    ],
    extras: ["Alas plat bordes / kalsifloor 20mm", "Tangga Rp 4.500.000/set (tinggi std 3m)"],
  },
];
